name: tasks

services:

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - 8080:4173

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: local
      DATABASE_HOST: db
      DATABASE_PASSWORD: password
      DATABASE_SSL: false
      DATABASE_NAME: 'Tasks'
      DATABASE_USERNAME: 'Tasks_owner'
      DATABASE_PORT: 5432
      PORT: 3000
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Tasks_owner
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Tasks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
