FROM node:21-alpine3.18 as base


FROM base as builder
WORKDIR /app
RUN npm install -g turbo
COPY . .
RUN turbo prune frontend --docker


FROM base as runner
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm install
 
COPY --from=builder /app/out/full/ .
RUN npx turbo run build --filter=frontend...

CMD ["npm", "run", "start:prod", "--prefix", "frontend"]
