POST http://localhost:3000/api/task-lists
Content-Type: application/json

{
  "name": "Tasks List 1",
  "tasksIds": [],
  "boardId": 1
}

###

GET http://localhost:3000/api/task-lists?boardId=1

###

DELETE  http://localhost:3000/api/task-lists/1