name: Publish gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"
          cache-dependency-path: '**/package-lock.json'
      - name: Install shared
        run: cd shared && npm install && npm run build:es
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Build
        run: cd frontend && API_URL="$API_URL" npm run build
        env:
          API_URL: ${{ vars.API_URL }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
